name: Generate Snake Animation

on:
  schedule:
    cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: webster-oss
          outputs: dist/snake.svg

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          message: Generate snake animation
          add: dist/snake.svg
          token:${{secrets.GITHUB_TOKEN}}
